dropout: 0.1
chara_nums: 800
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
num_channels: 128
num_res_blocks: 3
batch_size: 1
#num_samples: 50   #num_samples = m*bs
attention_resolutions: '40, 20, 10'
use_ddim: True
timestep_respacing: ddim10
model_path: 'trained_models/model250000.pt'
#sty_img_path: 'data/imgs/Seen_TRAIN800/id_0' #
cont_img_path:  'data/imgs/source_TEST'
total_txt_file: './TEST.txt'
#img_save_path: './result/models/sf40sc800/id_0'  #
classifier_free: True
cond_scale: 3.0
